site:
  title: 'Blog page - Timeline'
  description: 'Welcome to the blog timeline'
profile:
  name: 'Jefté Lima'
  avatar: https://github.com/jeftepl.png
  socialNetworks:
    github: https://github.com/jeftepl
