site:
  title: Blogrammer
  description: Welcome to your favorite blog about programming
profile:
  name: John Doe
  avatar: https://picsum.photos/300/300
  socialNetworks:
    github: https://github.com/
    youtube: https://youtube.com/
    instagram: https://instagram.com
    linkedin: https://linkedin.com
